version: "3.7"
services:
  express-session-test-with-mysql:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    depends_on:
      - mysql_srv
    environment:
      - DEBUG=express-session,session,express-mysql-session*
  mysql_srv:
    image: mysql:5.6
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
