version: "3"
services:
  express-session-test-with-redis:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    depends_on:
      - redis
    environment:
      - DEBUG=express-session,session
  redis:
    image: redis:6.0.5
    ports:
      - "6379:6379"
