version: "3.7"
services:
  express-session-test-with-mongo:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    depends_on:
      - mongo_srv
    environment:
      - DEBUG=express-session,session
  mongo_srv:
    image: mongo:3
    ports:
      - "27017:27017"
