version: "3.7"
services:
  express-session-test-with-mongo:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    depends_on:
      - mongo
    environment:
      - DEBUG=express-session,session
  mongo:
    image: mongo:3.6.18
    ports:
      - "27017:27017"
