name: on-publish-package
on:
  push:
    branches:
      - feat/express-as-service
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - "6379:6379"
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      express:
        image: docker.pkg.github.com/ghinks/express-integration-store/express-integration-redis-store:0.0.1
        ports:
          - 3000:3000
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm install
        run: npm ci
      - name: lerna bootstrap
        run: ./node_modules/.bin/lerna bootstrap
      - name: express-integration-tests
        run: ./packages/smoke-tests/node_modules/.bin/mocha packages/smoke-tests/lib/index.js
