name: NodeMatrix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        node: [12.18.2, 14.5.0]
    steps:
      - name: echo test value
        env:
          TEST_VALUE: ${{ secrets.ACTIONS_MY_TEST_STRING }}
          OTHER_VALUE: This is the other value
        run: echo "-------------------------------- $TEST_VALUE $OTHER_VALUE, this is the $PATH"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.0.0
        with:
          node-version: ${{ matrix.node }}
      - name: npm install
        run: npm ci
      - name: lerna bootstrap
        run: ./node_modules/.bin/lerna bootstrap
      - name: linting
        run: ./node_modules/.bin/lerna run lint
