name: on-publish-package
on:
  push:
    branches:
      - master
      - feature/publish-only-on-mster
  workflow_dispatch:
##################################################
#
# The intention of this actions file is to allow
# both npm packages to be published and docker
# images to be built in the build job.
# After the build job has successfully published
# then the integration testing using the published
# modules and images can take place in the one
# actions file.
# The docker image built in the build job is used
# in the integration job as a service.
#
##################################################
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ##################################################
      #
      # code checkout and node setup, this uses 2 actions
      # from the market place
      #
      ##################################################
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: setup-node-path
        run: echo '::add-path::./node_modules/.bin'
      ##################################################
      #   _           _ _     _
      #  | |__  _   _(_) | __| |
      #  | '_ \| | | | | |/ _` |
      #  | |_) | |_| | | | (_| |
      #  |_.__/ \__,_|_|_|\__,_|
      ##################################################

      ##################################################
      #   ____                  _
      #  / ___|   __ _    ___  | |__     ___
      # | |      / _` |  / __| | '_ \   / _ \
      # | |___  | (_| | | (__  | | | | |  __/
      #  \____|  \__,_|  \___| |_| |_|  \___|
      ##################################################
#      - name: restore lerna
#        uses: actions/cache@v2
#        with:
#          path: |
#            node_modules
#            */*/node_modules
#          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      ##################################################
      #
      # regular use of npm install command
      #
      ##################################################
      - name: npm-install
        run: npm ci
      ##################################################
      #
      #  A mono repo using lerna has been choosen for
      #  this project as it will test expressJS session
      #  behavior against several Database/storeage
      #  systems.
      #
      ##################################################
      - name: lerna-bootstrap
        run: lerna bootstrap
      ##################################################
      #
      # lerna bootstrap simply installs all the packages
      # in the mono repo. workspaces are an alternative
      #
      ##################################################
      - name: linting
        run: lerna run lint
      ##################################################
      #
      # conditional activity based on the branch
      #
      ##################################################
      - name: conditional-actions
        run: echo ${{ GITHUB_REF }}
