name: on-publish-package
on:
  push:
    branches:
      - docs/comment/steps
  workflow_dispatch:
##################################################
#
# The intention of this actions file is to allow
# both npm packages to be published and docker
# images to be built in the build job.
# After the build job has successfully published
# then the integration testing using the published
# modules and images can take place in the one
# actions file.
# The docker image built in the build job is used
# in the integration job as a service.
#
##################################################
jobs:
  ##################################################
  #    _____           _                                   _     _
  #   |_   _|         | |                                 | |   (_)
  #     | |    _ __   | |_    ___    __ _   _ __    __ _  | |_   _    ___    _ __
  #     | |   | '_ \  | __|  / _ \  / _` | | '__|  / _` | | __| | |  / _ \  | '_ \
  #    _| |_  | | | | | |_  |  __/ | (_| | | |    | (_| | | |_  | | | (_) | | | | |
  #   |_____| |_| |_|  \__|  \___|  \__, | |_|     \__,_|  \__| |_|  \___/  |_| |_|
  #                                  __/ |
  #                                 |___/
  #
  ##################################################
  integration:
    needs: build
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - "6379:6379"
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      express:
        image: ghinks/express-integration-redis-store:latest
        ports:
          - 3000:3000
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm install
        run: npm ci
      - name: lerna bootstrap
        run: ./node_modules/.bin/lerna bootstrap
      - name: express-integration-tests
        run: ./packages/smoke-tests/node_modules/.bin/mocha packages/smoke-tests/lib/index.js
